AsciiComments:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

ClassAndModuleChildren:
  EnforcedStyle: compact

AllCops:
  Exclude:
    - 'bin/*'
    - 'config/environments/*'
    - 'db/**/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'