version: "3"
volumes:
  mysql_8_0-data:
  vendor_bundle_2_5_1:
  vendor_assets_2_7:
  node_modules:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_8_0-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/comic
      - /comic/log
      - /comic/tmp
      - vendor_bundle_2_5_1:/comic/vendor/bundle
      - vendor_assets_2_7:/comic/vendor/assets
      - node_modules:/comic/node_modules
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
