version: "3"
volumes:
  mysql_8_0-data:
  vendor_bundle_2_5_1:
  vendor_assets_2_7:
  node_modules:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: mysql
    ports:
      - '3306:3306'
    volumes:
      - mysql_8_0-data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MYSQL_PASSWORD: password
    depends_on:
      - mysql
    volumes:
      - .:/comic
      - vendor_bundle_2_5_1:/comic/vendor/bundle
      - vendor_assets_2_7:/comic/vendor/assets
      - node_modules:/comic/node_modules
    tty: true
    stdin_open: true
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
