version: 2.1
jobs:
  # rspec:
  #   working_directory: ~/comic
  #   docker:
  #     - image: circleci/ruby:2.5.1
  #       environment:
  #         RAILS_ENV: test
  #   steps:
  #     - checkout
  #     - restore_cache:
  #       keys:
  #         - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
  #         - gem-cache-{{ arch }}-{{ .Branch }}
  #         - gem-cache
  #     - run:
  #       name: Bundle Install
  #       command: bundle check --path=vendor/bundle || bundle install --path vendor/bundle --clean --jobs 4 --retry 3
  #     - save_cache:
  #       key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
  #       paths:
  #         - ./vendor/bundle
  #     - run:
  #         name: Setup database
  #         command: |
  #           bundle exec rails db:create
  #           bundle exec rails db:migrate
  #           bundle exec rails db:seed
  #     - run:
  #         name: Run rspec
  #         command: bundle exec rspec

  rubocop:
    working_directory: ~/comic
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  heroku_deploy:
    working_directory: ~/comic
    docker:
      - image: sue445/heroku-cli
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - run:
          name: Deploy
          command: |
            heroku config:set RAILS_MASTER_KEY=$RAILS_MASTER_KEY
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Run post-deploy tasks
          command: |
            heroku git:remote -a $HEROKU_APP_NAME
            heroku run rails db:migrate

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
workflows:
  version: 2.1
  build:
    jobs:
      # - rspec
      - rubocop
      - heroku_deploy:
          context: BUILD_CIRCLECI
          requires:
            # - rspec
            - rubocop
